"""empty message

Revision ID: cfc517e92c04
Revises: 
Create Date: 2023-06-07 22:10:59.955701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfc517e92c04'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('base_rate_per_hour', sa.Integer(), nullable=False),
    sa.Column('base_rate_per_km', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_category_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_category_name'), ['name'], unique=False)

    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('full_name', sa.String(length=80), nullable=False),
    sa.Column('profile_image_name', sa.String(length=255), nullable=True),
    sa.Column('profile_image_url', sa.String(length=1000), nullable=True),
    sa.Column('email', sa.String(length=80), nullable=False),
    sa.Column('phone_number', sa.String(length=13), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_full_name'), ['full_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_phone_number'), ['phone_number'], unique=True)

    op.create_table('current_location',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('current_location', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_current_location_id'), ['id'], unique=False)

    op.create_table('location_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('location_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_location_history_id'), ['id'], unique=False)

    op.create_table('order',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('desc', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.Column('assigned_labor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_labor_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_order_id'), ['id'], unique=False)

    op.create_table('reviews',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('review_val', sa.Float(), nullable=True),
    sa.Column('total_reviews', sa.Integer(), nullable=True),
    sa.Column('labor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['labor_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reviews_id'), ['id'], unique=False)

    op.create_table('token_blocklist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(length=36), nullable=False),
    sa.Column('token_type', sa.String(length=10), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('expires', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jti')
    )
    op.create_table('bill',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('base_rate', sa.Float(), nullable=False),
    sa.Column('hours', sa.Integer(), nullable=False),
    sa.Column('minutes', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('is_paid', sa.Boolean(), nullable=True),
    sa.Column('payment_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bill', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bill_id'), ['id'], unique=False)

    op.create_table('current_active_order',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('labor_id', sa.Integer(), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.Column('current_active_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['current_active_order'], ['order.id'], ),
    sa.ForeignKeyConstraint(['labor_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('current_active_order', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_current_active_order_id'), ['id'], unique=False)

    op.create_table('labor_detail',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('labor_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('reviews_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['labor_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['reviews_id'], ['reviews.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('labor_detail', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_labor_detail_id'), ['id'], unique=False)

    op.create_table('reviews_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('review_val', sa.Float(), nullable=True),
    sa.Column('labor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['labor_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reviews_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reviews_history_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reviews_history_id'))

    op.drop_table('reviews_history')
    with op.batch_alter_table('labor_detail', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_labor_detail_id'))

    op.drop_table('labor_detail')
    with op.batch_alter_table('current_active_order', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_current_active_order_id'))

    op.drop_table('current_active_order')
    with op.batch_alter_table('bill', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bill_id'))

    op.drop_table('bill')
    op.drop_table('token_blocklist')
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reviews_id'))

    op.drop_table('reviews')
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_id'))

    op.drop_table('order')
    with op.batch_alter_table('location_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_location_history_id'))

    op.drop_table('location_history')
    with op.batch_alter_table('current_location', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_current_location_id'))

    op.drop_table('current_location')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_phone_number'))
        batch_op.drop_index(batch_op.f('ix_user_full_name'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_category_name'))
        batch_op.drop_index(batch_op.f('ix_category_id'))

    op.drop_table('category')
    # ### end Alembic commands ###
